outbox: RuntimeError: dictionary changed size during iteration
This should fix the issue tested. Before issue show up few times per hour not happen any more.

Reproducing very difficult,  comes side effect. 

list take copy of items therefore dictionary size cannot change during iteration anymore.

Error message:
dictionary changed size during iteration
Traceback (most recent call last):
  File "/home/hsyrja/.local/lib/python3.10/site-packages/nicegui/outbox.py", line 49, in loop
    data = {
  File "/home/hsyrja/.local/lib/python3.10/site-packages/nicegui/outbox.py", line 49, in <dictcomp>
    data = {
RuntimeError: dictionary changed size during iteration