Warn accidental script mode due only to `ui.add_*` without `shared=True` (#5478)
### Motivation

As see in
https://github.com/zauberzeug/nicegui/issues/5472#issue-3645073473, it
is easy to accidentally invoke NiceGUI script mode due to use of
`ui.add_head_html` or other `ui.add_*` functions without `shared=True`

```py
from nicegui import ui

ui.add_head_html('''
    <style>
        .my-red-label {
            color: Crimson;
            font-weight: bold;
        }
    </style>
''')

@ui.page('/')
async def root():
    ui.label('RED').classes('my-red-label')

ui.run()
```

Without knowledge in NiceGUI inner-workings, the following error message
is quite a head-scratcher.

```
RuntimeError: ui.page cannot be used in NiceGUI scripts where you define UI in the global scope. To use multiple pages, either move all UI into page functions or use ui.sub_pages.
```

### Implementation

This PR detects such accidental invocations of NiceGUI script mode by
checking for both:

- No other elements in the script mode client's content
- Either `_body_html` or `_head_html` was set

And provides a message with action to resolve this issue. 

```
Note: You had no other UI elements in the global scope than ui.add_head_html / ui.add_body_html / ui.add_css. 
To resolve the RuntimeError below, consider using shared=True, as they do not constitute UI elements. 
```

### Progress

- [x] I chose a meaningful title that completes the sentence: "If
applied, this PR will..."
- [x] The implementation is complete.
- [x] Pytests are not necessary (we don't test script mode).
- [x] Documentation is not necessary (self-explanatory).

---------

Co-authored-by: Falko Schindler <falko@zauberzeug.com>